### ISSUE TITLE
Include limitations of bounter in ReadMe for non-power users.

### ISSUE THREAD

**Issue by aneesh-joshi** [RaRe-Technologies/bounter#36]
As per the discussion [here]( https://news.ycombinator.com/item?id=15521177), I think it would be good to include a section like:

## Where bounter fails/is inaccurate/Accuracy TradeOffs
I refer to the part below:
>The introduction is misleading about what tradeoffs it makes
  >>> from bounter import bounter
  >>> bounts = bounter(size_mb=1)
  >>> bounts.update(str(i) for i in xrange(1000000))
  >>> bounts['100']
  0L
should give 1. The description should be more upfront that you are getting inaccurate answers.
> Bounter implements approximative algorithms using optimized low-level C structures, to avoid the overhead of Python objects.

"approximative algorithms" isn't a commonly used phrase (at least according to Google) and this sentence doesn't say anything about what the actual trade-off is (loss of accuracy in the counts). A possible alternative would be writing to hard disk so what trade-off is made isn't obvious.

I also don't know what the precision and recall percentages in the example table mean
It will be good for new comers/non-power users.

Wdyt @menshikh-iv ?

I would be glad to make a PR for this.

**Comment by menshikh-iv** [comment]
More informative description sounds like a good idea to me @aneesh-joshi
