### ISSUE TITLE
Add unit tests for count min sketch

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/bounter#7]
Implement unit tests for all major functions.

All tests should go in their own (sub)directory, as prepared in #8 .

**Comment by piskvorky** [comment]
@menshikh-iv is this ticket really solved? Re-opening.

**Comment by menshikh-iv** [comment]
@piskvorky  no, sorry, I closed only #8, current issue was closed in an automatic way.

**Comment by isamaru** [comment]
Unit tests added for both CMS and HashTable, CI works great now!
